// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

// TODO: ideally, this file should be generated by the Q# compiler alongside the qir

#pragma once

#include <string>
#include <unordered_map>

#include "TracerTypes.hpp"

namespace TracerUser
{
extern const std::unordered_map<Microsoft::Quantum::OpId, std::string> g_operationNames;
} // namespace TracerUser

// Available function in generated QIR
extern "C" void Microsoft__Quantum__Testing__Tracer__TestCoreIntrinsics__body(); // NOLINT
extern "C" void Microsoft__Quantum__Testing__Tracer__TestMeasurements__body(); // NOLINT
