[workspace]

members = [
    "src/Simulation/qdk_sim_rs",
    "src/Qir/riqir/runtime",
    "src/Qir/riqir/sim",
]

[profile.release]
codegen-units = 1   # Reduce number of codegen units to increase optimizations.
opt-level = 3
panic = 'unwind'
