[package]
name = "qir-runtime"
version = "0.1.0"
authors = ["Microsoft"]
edition = "2021"

[dependencies]
num-bigint = { version = "0.4.3", default-features = false }
rand = "0.8.5"

[lib]
crate-type = ["cdylib","rlib"]
