[package]
name = "qir-stdlib"
version = "0.1.0"
authors = ["Microsoft"]
edition = "2021"
license = "MIT"

[dependencies]
qir-stdlib = { git = "https://github.com/qir-alliance/qir-runner/", rev = "54d334c0c845ebbfd4dc9512ef05cd2cbe4238c5" }

[lib]
crate-type = ["staticlib"]
