// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

// TODO: ideally, this file should be generated by the Q# compiler alongside the qir, using the mappings specified in
// target.qs.

#include <memory>

#include "QuantumApi_I.hpp"
#include "tracer-config.hpp"

namespace TracerUser
{
const std::unordered_map<Microsoft::Quantum::OpId, std::string> g_operationNames = {
    {0, "X"}, {1, "CX"}, {2, "MCX"}, {3, "Y"}, {4, "CY"}, {5, "MCY"} /*etc.*/};
}
