// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// TODO: ideally, this file should be generated by the Q# compiler alongside the qir

#pragma once

#include <string>
#include <unordered_map>

namespace Microsoft
{
namespace Quantum
{
    using OpId = int;
    using Time = int;
    using Duration = int;
    using LayerId = size_t;
}
}

namespace TracerUser
{
using OpId = int;
extern const std::unordered_map<Microsoft::Quantum::OpId, std::string> g_operationNames;
} // namespace TracerUser

// Available function in generated QIR
extern "C" bool Microsoft__Quantum__Testing__Tracer__AllIntrinsics__body(); // NOLINT
