# This action allows using the automerge label to automatically merge in pull requests that have been reviewed and that pass
# status checks (similar to the autocomplete functionality of Azure DevOps).
name: automerge
on:
  pull_request:
    # Note that we only support automerge on branches that have required checks.
    branches: 
      - master
      - feature/*
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    # Note that we only support automerge on branches that have required checks.
    branches: 
      - master
      - feature/*
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@4536e8847eb62fe2f0ee52c8fa92d17aa97f932f"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_METHOD: squash
